NAME	=	no_you_need_form_28b_not_28c

SRC		=	main.cpp\
			Bureaucrat.cpp\
			Form.cpp\
			ShrubberyCreationForm.cpp\
			RobotomyRequestForm.cpp\
			PresidentialPardonForm.cpp\


LOG		=	-DLOG

SHRUBBERY =	*_shrubbery

# CXXFLAGS +=	 -Wshadow

include ../Makefile
