NAME	=	at_least_this_beats_coffee_making

SRC		=	main.cpp\
			Bureaucrat.cpp\
			Form.cpp\
			ShrubberyCreationForm.cpp\
			RobotomyRequestForm.cpp\
			PresidentialPardonForm.cpp\
			Intern.cpp


LOG		=	-DLOG

SHRUBBERY =	*_shrubbery

# CXXFLAGS +=	 -Wshadow

include ../Makefile
